#!/usr/bin/expect -f
#
spawn telnet localhost 7000
expect "Trying 127.0.0.1..."
expect "Connected to localhost."
expect "Escape character is '^]'."
log_file testserver1.out
send "Dit is een test.\r"
expect "READY"
log_file 
