#!/usr/bin/expect -f
#
spawn telnet localhost 7000
expect "Trying 127.0.0.1..."
expect "Connected to localhost."
expect "Escape character is '^]'."
log_file -noappend testjsonserver2.out
send { [{"sentence":"Dit nog zo'n boeiende test."}] }
send "\r"
expect -re ".*\n" # the echoed send
expect -re ".*\n" # the echoed return
expect -re ".*\n" # the received json
send "\r"
send_log "\r\n"
log_file
