#!/usr/bin/expect -f
#
spawn telnet localhost 7000
expect "Trying 127.0.0.1..."
expect "Connected to localhost."
expect "Escape character is '^]'."
log_file -noappend testserver3.out
send "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
send "<FoLiA xmlns=\"http://ilk.uvt.nl/folia\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" xml:id=\"WR-P-E-J-0000000001\" version=\"0.8\" generator=\"libfolia-v0.4\">\n"
send "  <metadata type=\"imdi\">\n"
send "    <annotations>\n"
send "      <division-annotation annotator=\"ucto\" annotatortype=\"auto\" set=\"div\"/>\n"
send "    </annotations>\n"
send "  </metadata>\n"
send "  <text xml:id=\"WR-P-E-J-0000000001.text\">\n"
send "      <div xml:id=\"WR-P-E-J-0000000001.div0.1\" class=\"hst\">\n"
send "        <head xml:id=\"WR-P-E-J-0000000001.head.1\">\n"
send "          <s xml:id=\"WR-P-E-J-0000000001.head.1.s.1\">\n"
send "	    <t>Dit is een test van FoLia input?</t>\n"
send "	  </s>\n"
send "	</head>\n"
send "      </div>\n"
send "  </text>\n"
send "</FoLiA>\n"
send "\n"
expect "READY"
send_log "\r\n"
log_file
