#!/bin/sh

$frog_bin/frog -S 7000  > testserver.log 2>&1  &
pid=`echo $!`

sleep 30

./frogclient5 &
./frogclient6 &

sleep 20
cat testserver5.out > testserver.out
cat testserver6.out >> testserver.out

kill $pid

sleep 5
