#!/bin/sh

\rm testserverxml-*.log

$frog_bin/frog -x --skip=p -S 7000  > testserverxml-1.log 2>&1  &
pid=`echo $!`

if [ `uname` = Darwin ]
then
    sleep 30
else
    count="0"
    stat="0"
    while [ $stat -ne 1 ]
    do
	#	echo `lsof -i :7000 |grep -c LISTEN`
	stat=`lsof -i :7000 |grep -c LISTEN`
	echo count=$count
	echo status=$stat
	count=$((count+1))
	if [ $count -ge 20 ]; then
	    echo "unable to start server in time..."
	    exit 1
	fi
	sleep 1
    done
fi

\rm  testserver3.out
\rm  testserver4.out

./frogclient3 &
pids[0]=$!
./frogclient4 &
pids[1]=$!

echo "created PID's: ${pids[*]}"
for sub_pid in ${pids[*]}
do
    wait $sub_pid
done

echo "done waiting"

grep -v '<' testserver3.out > testserverxml.out
grep '<' testserver3.out > testserverxml.1.xml
$folialint --nooutput testserverxml.1.xml >> testserverxml.out 2>&1
grep -v '<' testserver4.out >> testserverxml.out
grep '<' testserver4.out > testserverxml.2.xml
$folialint --nooutput testserverxml.2.xml >> testserverxml.out 2>&1

kill $pid
wait $pid

$frog_bin/frog -x -X --KANON --skip=p -S 7000  > testserverxml-2.log 2>&1  &
pid=`echo $!`

if [ `uname` = Darwin ]
then
    sleep 30
else
    count="0"
    stat="0"

    while [ $stat -ne 1 ]
    do
	#       echo `lsof -i :7000 |grep -c LISTEN`
	stat=`lsof -i :7000 |grep -c LISTEN`
	#    echo count=$count
	#    echo status=$stat
	count=$((count+1))
	if [ $count -ge 20 ]; then
	    echo "unable to start server in time..."
	    exit 1
	fi
	sleep 1
    done
fi

\rm  testserver3.out
\rm  testserver4.out

./frogclient3 &
pids2[0]=$!
./frogclient4 &
pids2[1]=$!

echo "created PID's: ${pids2[*]}"
for sub_pid in ${pids2[*]}
do
    wait $sub_pid
done

echo "done waiting"
\rm awkout*
\rm awkclean*

awk -v RS='\n\r' '{print > ("awkout.3-" NR ".xml")}' testserver3.out
$folialint --nooutput awkout.3-1.xml >> testserverxml.out 2>&1
cat awkout.3-2.xml >> testserverxml.out
grep "<" awkout.3-3.xml > awkclean.3.3.xml
$folialint --nooutput awkclean.3.3.xml >> testserverxml.out 2>&1

awk -v RS='\n\r' '{print > ("awkout.4-" NR ".xml")}' testserver4.out
$folialint --nooutput awkout.4-1.xml >> testserverxml.out 2>&1
cat awkout.4-2.xml >> testserverxml.out
grep "<" awkout.4-3.xml > awkclean.4.3.xml
$folialint --nooutput awkclean.4.3.xml >> testserverxml.out 2>&1


kill $pid
wait $pid

$frog_bin/frog -X --KANON --skip=p -S 7000  > testserverxml-3.log 2>&1  &
pid=`echo $!`

if [ `uname` = Darwin ]
then
    sleep 30
else
    count="0"
    stat="0"

    while [ $stat -ne 1 ]
    do
	#       echo `lsof -i :7000 |grep -c LISTEN`
	stat=`lsof -i :7000 |grep -c LISTEN`
	#    echo count=$count
	#    echo status=$stat
	count=$((count+1))
	if [ $count -ge 20 ]; then
	    echo "unable to start server in time..."
	    exit 1
	fi
	sleep 1
    done
fi

\rm  testserver6.out
\rm  testserver7.out

./frogclient6 &
pids3[0]=$!
./frogclient7 &
pids3[1]=$!

echo "created PID's: ${pids3[*]}"
for sub_pid in ${pids3[*]}
do
    wait $sub_pid
done

echo "done waiting"

grep "<" testserver6.out > testserverxml.6.xml
$folialint --nooutput testserverxml.6.xml >> testserverxml.out 2>&1
grep "<" testserver7.out > testserverxml.7.xml
$folialint --nooutput testserverxml.7.xml >> testserverxml.out 2>&1

kill $pid
wait $pid
\rm awkout*
\rm awkclean*
