#!/bin/sh
#
# defaults:
#

rm ./mbmaout/*
rm ./output/*

$comm --TESTAPI -t teststandard.txt > testapi.out

$comm --skip=p --TESTAPI --testdir mbmaproblems >> testapi.out

$comm --skip=p --TESTAPI --testdir xmltests >> testapi.out

cat <<EOF > dm.txt
Een test met een verzekeringsagent.
En een toevalstreffer.
presidents
EOF
$comm --skip=p --TESTAPI --deep-morph dm.txt >> testapi.out
