#!/bin/sh
#
# defaults:
#

rm ./mbmaout/*

$comm -t ./mbmaproblems/bons --debug=a0 --daring -X bons.xml --KANON > testdaring.out
cat bons.xml >> testdaring.out
$comm -t ./mbmaproblems/torture --debug=a0 --daring -X torture.xml --KANON >> testdaring.out
cat torture.xml >> testdaring.out

$comm -t ./mbmaproblems/torture2 --debug=a0 --daring -X torture2.xml --KANON >> testdaring.out
cat torture2.xml >> testdaring.out
