#!/bin/sh -x
$frog_bin/frog  --keep-parser-files -n -S 7000  > testserver-n.log 2>&1  &
pid=`echo $!`

count="0"
stat="0"
while [ $stat -ne 1 ]
do
#    echo `lsof -i :7000 |grep -c LISTEN`
    stat=`lsof -i :7000 |grep -c LISTEN`
#    echo count=$count
#    echo status=$stat
    count=$((count+1))
    if [ $count -ge 20 ]; then
	echo "unable to start server in time..."
	exit 1
    fi
    sleep 1
done

./frogclient1 &
pids[0]=$!
./frogclient2 &
pids[1]=$!

echo "created PID's: ${pids[*]}"
for sub_pid in ${pids[*]}
do
    wait $sub_pid
done

echo "done waiting"

sleep 5

cat testserver1.out > testserver-n.out
cat testserver2.out >> testserver-n.out

kill $pid
sleep 5
