#!/bin/sh -x


$frog_bin/frog -x --skip=p -S 7000  > testserverxml-1.log 2>&1  &
pid=`echo $!`

count="0"
stat="0"

while [ $stat -ne 1 ]
do
#    echo `lsof -i :7000 |grep -c LISTEN`
    stat=`lsof -i :7000 |grep -c LISTEN`
#    echo count=$count
#    echo status=$stat
    count=$((count+1))
    if [ $count -ge 20 ]; then
	echo "unable to start server in time..."
	exit 1
    fi
    sleep 1
done

\rm  testserver3.out
\rm  testserver4.out

./frogclient3 &
./frogclient4 &

sleep 5
cat testserver3.out > testserverxml.out
cat testserver4.out >> testserverxml.out

kill $pid
sleep 5

$frog_bin/frog -x -X --KANON --skip=p -S 7000  >> testserverxml-2.log 2>&1  &
pid=`echo $!`

count="0"
stat="0"

while [ $stat -ne 1 ]
do
#    echo `lsof -i :7000 |grep -c LISTEN`
    stat=`lsof -i :7000 |grep -c LISTEN`
#    echo count=$count
#    echo status=$stat
    count=$((count+1))
    if [ $count -ge 20 ]; then
	echo "unable to start server in time..."
	exit 1
    fi
    sleep 1
done

\rm  testserver3.out
\rm  testserver4.out

./frogclient3 &
./frogclient4 &

sleep 5
cat testserver3.out >> testserverxml.out
cat testserver4.out >> testserverxml.out

kill $pid
sleep 5
