#!/bin/sh -x

$frog_bin/frog -S 7000  > testserver.log 2>&1  &
pid=`echo $!`

count="0"
stat="0"
while [ $stat -ne 1 ]
do
#    echo `lsof -i :7000 |grep -c LISTEN`
    stat=`lsof -i :7000 |grep -c LISTEN`
#    echo count=$count
#    echo status=$stat
    count=$((count+1))
    if [ $count -ge 20 ]; then
	echo "unable to start server in time..."
	exit 1
    fi
    sleep 1
done


./frogclient5 &
./frogclient6 &

sleep 8

cat testserver5.out > testserver.out
cat testserver6.out >> testserver.out

kill $pid

sleep 5
