#!/bin/sh
#
# defaults:
#

rm ./mbmaout/*

$comm --skip=mpcn -t ./mbmaproblems/bons --debug=a0 --deep-morph -X bons.xml --KANON > testdaring.out
$foliadiff bons.xml goodresults/bons.xml >> testdaring.out

$comm  --skip=mpcn -t ./mbmaproblems/torture --debug=a0 --deep-morph -X torture.xml --KANON >> testdaring.out
$foliadiff torture.xml goodresults/torture.xml >> testdaring.out

$comm  --skip=mpcn -t ./mbmaproblems/tortuur --debug=a0 --deep-morph -X tortuur.xml --KANON >> testdaring.out
$foliadiff tortuur.xml goodresults/tortuur.xml >> testdaring.out

$comm  --skip=mpcn -t ./mbmaproblems/compounds --debug=a0 --deep-morph -X compounds.xml --KANON >> testdaring.out
$foliadiff compounds.xml goodresults/compounds.xml >> testdaring.out

$comm  -t mwu.txt --debug=a0 --deep-morph -X mwu.xml --KANON >> testdaring.out
$foliadiff mwu.xml goodresults/mwu.xml >> testdaring.out

$comm  --skip=mpcn -t ./mbmaproblems/fixtest --debug=a0 --deep-morph -X fixtest.xml --KANON >> testdaring.out
$foliadiff fixtest.xml goodresults/fixtest.xml >> testdaring.out
