#!/bin/sh -x


$frog_bin/frog  --keep-parser-files=yes -S 7000  > testserver.log 2>&1  &
pid=`echo $!`

sleep 12

./frogclient5 &
./frogclient6 &

sleep 4
cat testserver5.out > testserver.out
cat testserver6.out >> testserver.out

kill $pid

