#!/bin/sh
#
# defaults:
#

$comm --skip=pt -t teststandard.txt -o testpassthru.txt -X testpassthru.xml
$foliadiff testpassthru.xml goodresults/testpassthru.xml >> testpassthru.out
cat testpassthru.txt >> testpassthru.out
