#!/bin/sh
#
# defaults:
#

rm ./output/*
rm *.out.xml*
rm ./zipoutput/*
rm ./strangeout/*

echo "test 1: " > testxmlin.out
$comm --skip=p -x folia1.xml -X folia1.out.xml --KANON
$folialint folia1.out.xml >> testxmlin.out
echo "test 2: " >> testxmlin.out
$comm --skip=p -x folia1.xml --inputclass=OCR -X folia2.out.xml --KANON
$folialint folia2.out.xml >> testxmlin.out
echo "test 3: " >> testxmlin.out
$comm --skip=p -t folia1.xml --inputclass=OCR --outputclass=NEW -X folia3.out.xml --KANON >> testxmlin.out
$folialint folia3.out.xml >> testxmlin.out
echo "test 4: " >> testxmlin.out
$comm --skip=p -x folia1.xml --outputclass=NEW -X folia4.out.xml --KANON
$folialint folia4.out.xml >> testxmlin.out
echo "test 5: " >> testxmlin.out
$comm --skip=p -t folia1.xml.gz -X folia1.out.5.xml.gz --KANON
gunzip -c folia1.out.5.xml.gz >> testxmlin.out
$folialint folia1.out.5.xml >> testxmlin.out
echo "test 6: " >> testxmlin.out
$comm --skip=p -t folia1.xml.bz2 -X folia1.out.6.xml.bz2 --KANON
bzcat folia1.out.6.xml.bz2 >> testxmlin.out
$folialint folia1.out1.xml.bz2 >> testxmlin.out
echo "test 7: " >> testxmlin.out
$comm --skip=p -t folia1.xml -X folia1.out.7.xml --KANON >> testxmlin.out
$folialint --nooutput folia1.out.7.xml >> testxmlin.out
echo "test 8: " >> testxmlin.out
$comm --skip=p -x folia1.xml --testdir=xmltests -X folia1.out.8.xml --KANON >> testxmlin.out
echo "test 9: " >> testxmlin.out
$comm --skip=p --KANON -x --testdir=xmltests --xmldir=./output
$folialint ./output/folia1.xml >> testxmlin.out
echo "test 9a: " >> testxmlin.out
$folialint ./output/folia2.xml >> testxmlin.out
echo "test 9b: " >> testxmlin.out
$folialint ./output/folia3.xml >> testxmlin.out
echo "test 9c: " >> testxmlin.out
$folialint ./output/folia4.xml >> testxmlin.out
echo "test 9d: " >> testxmlin.out
$folialint ./output/spaces.xml >> testxmlin.out
echo "test 10: " >> testxmlin.out
$comm -x xmltests/folia4.xml -X folia10.out.xml --KANON
$folialint folia10.out.xml >> testxmlin.out
echo "test 11: " >> testxmlin.out
$comm --skip=p -x --testdir=zipxmltests --xmldir=./zipoutput
$foliadiff ./zipoutput/folia1.xml.bz2 folia1.zip.ok.bz2 >> testxmlin.out
$foliadiff ./zipoutput/folia2.xml.gz folia2.zip.ok.gz >> testxmlin.out
$foliadiff ./zipoutput/folia3.xml.bz2 folia3.zip.ok.bz2 >> testxmlin.out
echo "test 12: " >> testxmlin.out
$comm -x --testdir=strangefolia --xmldir=./strangeout --outputdir=./strangeout
$foliadiff ./strangeout/issue064b.xml issue064b.ok >> testxmlin.out
$foliadiff ./strangeout/issue064c.xml issue064c.ok >> testxmlin.out
